apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  name: apr-nginx-helm
  project: giri-prod-test
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-apr-prod2
    - key: rafay.dev/clusterName
      value: giri-apr6-prod
  resourceQuotas: {}
