apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: prod-ns
  project: giri-prod-test
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-prod-post-rollout
  resourceQuotas: {}
