apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: redis
  project: giri-prod-test
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-july-prod-aks
    - key: rafay.dev/clusterName
      value: giri-prod-oct14
  resourceQuotas: {}
