apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  annotations:
    rafay.dev/description: ""
  labels:
    a1: b1
  name: sep26
  project: giri-prod-test
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  networkPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-prod-sep26
  resourceQuotas: {}
